image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${DOCKER_IMAGE_VERSION}

stages:
  - test
  - translate_report
  - deploy

regression_test_job:
  stage: test
  when: manual
  tags:
  - docker-prod
  image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_PERFORMANCE}:${DOCKER_IMAGE_PERFORMANCE_VERSION}
  script:
  - npm install -g yarn
  - yarn
  - yarn bootstrap
  - npm run build
  - npm run test
  - npm run integration-test
  - npm run functional-test
  - npm run api-breaks-test
  - cp ./tests/integration/api-breaks/xunit.xml $CI_PROJECT_DIR/api-breaks-xunit.xml
  - cp ./tests/integration/xunit.xml $CI_PROJECT_DIR/integration-xunit.xml
  - cp ./tests/functional/xunit.xml $CI_PROJECT_DIR/reports/api-breaks-xunit.xml
  - cp ./@here/olp-sdk-authentication/xunit.xml $CI_PROJECT_DIR/olp-sdk-authentication-xunit.xml
  - cp ./@here/olp-sdk-core/xunit.xml $CI_PROJECT_DIR/olp-sdk-core-xunit.xml
  - cp ./@here/olp-sdk-dataservice-api/xunit.xml $CI_PROJECT_DIR/olp-sdk-dataservice-api-xunit.xml
  - cp ./@here/olp-sdk-dataservice-read/xunit.xml $CI_PROJECT_DIR/olp-sdk-dataservice-read-xunit.xml
  - cp ./@here/olp-sdk-dataservice-write/xunit.xml $CI_PROJECT_DIR/olp-sdk-dataservice-write-xunit.xml
  - cp ./@here/olp-sdk-fetch/xunit.xml $CI_PROJECT_DIR/olp-sdk-fetch-xunit.xml
  only:
    - master
  artifacts:
    when: always
    paths:
      - ./*.xml
    expire_in: 1 year # save for 1 year as job artifacts

regression_generate_report_job:
  stage: translate_report
  when: manual
  tags:
  - docker-prod
  image: python:3.6
  before_script:
    - pip install junit2html
  script:
    - python -m junit2htmlreport --report-matrix index.html ./*.xml
    - mkdir -p .public
    - cp index.html .public/
  artifacts:
    paths:
      - .public
  only:
    refs:
      - master

release_verify_job:
  stage: test
  tags:
  - docker-prod
  image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_PERFORMANCE}:${DOCKER_IMAGE_PERFORMANCE_VERSION}
  script:
  - npm install -g yarn
  - yarn
  - yarn bootstrap
  - npm run build
  - npm run test-published-bundles
  when: manual
  only:
    - master

weekly_security_test_job:
  stage: test
  tags:
  - docker-prod
  script:
  - $CI_PROJECT_DIR/scripts/security-scanner/SecurityScannerUpload.sh build/olp-edge-ts.zip OLP_EDGE_CI@here.com
  only:
    refs:
      - master
      - schedules
    variables:
      - $SECURITY
  artifacts:
    when: always
    paths:
      - build
    expire_in: 1 year # save our zip for 1 year as job artifacts

nightly_perf_publish_test_job:
  stage: test
  tags:
  - docker-prod
  image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_PERFORMANCE}:${DOCKER_IMAGE_PERFORMANCE_VERSION}
  script:
  - $CI_PROJECT_DIR/scripts/linux/nv/gitlab_test_performance.sh
  - $CI_PROJECT_DIR/scripts/linux/nv/gitlab_test_publish_dryrun.sh
  only:
    refs:
      - master
      - schedules
    variables:
      - $NIGHTLY
  artifacts:
    when: always
    paths:
      - ./*.gz
      - ./*.html
      - cache
      - heaptrack
      - reports
    expire_in: 1 year # save our archives for 1 year as job artifacts

weekly_perf_test_job:
  stage: test
  tags:
  - docker-prod
  image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE_PERFORMANCE}:${DOCKER_IMAGE_PERFORMANCE_VERSION}
  script:
  - $CI_PROJECT_DIR/scripts/linux/wv/gitlab_test_performance_extended.sh
  only:
    refs:
      - master
      - schedules
    variables:
      - $WEEKLY
  artifacts:
    when: always
    paths:
      - ./*.gz
      - ./*.html
      - cache
      - heaptrack
      - reports
    expire_in: 1 year # save our archives for 1 year as job artifacts
    
    # next stages will run on NV and WK jobs

generate_perf_report_job:
  stage: translate_report
  tags:
  - docker-prod
  image: python:3.6
  when: always
  before_script:
    - pip install junit2html
  script:
    - if [ "$NIGHTLY" == "1" ]; then cat heaptrack_report.html >> reports/index.html; fi
    - if [ "$WEEKLY" == "1" ]; then cat heaptrack_report.html >> reports/index.html; fi
    - mkdir -p .public
    - cp reports/*.html .public/
  artifacts:
    paths:
      - .public
  only:
    refs:
      - master
      - schedules
    variables:
      - $WEEKLY
      - $NIGHTLY

pages:
  stage: deploy
  tags:
    - docker-prod
  when: always
  script: mv .public public
  artifacts:
    paths:
      - public
    expire_in: 1 year
  only:
    refs:
      - master
      - schedules
    variables:
      - $WEEKLY
      - $NIGHTLY
