trigger:
- master
pr:
- master

variables:
  BUILD_TYPE: "RelWithDebInfo"

jobs:
- job: Commit_checker
  pool:
    vmImage: 'ubuntu-latest'
  condition: eq(variables['Build.Reason'], 'PullRequest')
  steps:
    - bash: scripts/misc/commit_checker.sh
      displayName: 'Commit checker script'
