coverage:
  range: 60..100
  round: up
  precision: 4
  status:
    project:
      authentication:
        paths:
          - ./@here/olp-sdk-authentication
        threshold: 1
      dataservice-read:
        paths:
          - ./@here/olp-sdk-dataservice-read
        threshold: 1
      dataservice-write:
        paths:
          - ./@here/olp-sdk-dataservice-write
        threshold: 1
      olp-sdk-fetch:
        paths:
          - ./@here/olp-sdk-fetch
        threshold: 1
      olp-sdk-dataservice-api:
        paths:
          - ./@here/olp-sdk-dataservice-api
        threshold: 1
ignore:
  - ./@here/olp-sdk-authentication/test
  - ./@here/olp-sdk-dataservice-read/test
  - ./@here/olp-sdk-fetch/test
  - ./@here/olp-sdk-dataservice-api/test
  - ./@here/olp-sdk-dataservice-write/test
  - tests
  - scripts
  - docs