name: Typescript PSV CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  psv-linux-build-test-codecov:
    name: PSV / Linux Build / Tests / Code coverage
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: npm
    - name: Build / Tests / Coverage
      run: scripts/linux/psv/build_test_psv.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  psv-commit-checker:
    name: PSV.Commit.Checker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Commit checker script. Verify commit text
      run: scripts/misc/commit_checker.sh
      shell: bash

